"""
GeoSignal Dashboard - Geopolitical Trading Signals
Deployed on GitHub Pages with server-side data fetching

Reads pre-fetched JSON data files (generated by fetch_all_data.py via GitHub Actions)
API keys never exposed in frontend HTML/CSS/JS!
"""

import streamlit as st
import json
import os
from datetime import datetime

# Page configuration - no API keys needed for static rendering!
st.set_page_config(
    page_title="GeoSignal — Geopolitical Signal Agent",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Load data from JSON files (pre-fetched by GitHub Actions)
def load_data():
    """Load pre-fetched JSON data"""
    with open('data/signals.json', 'r') as f:
        signals = json.load(f)['signals']
    
    with open('data/markets.json', 'r') as f:
        markets = json.load(f)['markets']
    
    with open('data/whales.json', 'r') as f:
        whales = json.load(f)
    
    with open('data/articles.json', 'r') as f:
        articles = json.load(f)['articles']
    
    return signals, markets, whales, articles

# Load data once on startup
signals, markets, whales_data, articles = load_data()

# Custom CSS for better styling
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        text-align: center;
        padding: 2rem 0;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 10px;
        margin-bottom: 2rem;
    }
    .signal-card {
        padding: 1.5rem;
        margin: 1rem 0;
        border-radius: 10px;
        border-left: 5px solid;
    }
    .critical { border-left-color: #dc3545; background-color: #f8d7da; }
    .high { border-left-color: #fd7e14; background-color: #fff3cd; }
    .medium { border-left-color: #ffc107; background-color: #fff3cd; }
    .low { border-left-color: #6c757d; background-color: #f8f9fa; }
</style>
""", unsafe_allow_html=True)

# Main header
st.markdown('<div class="main-header">🌍 GeoSignal Dashboard</div>', unsafe_allow_html=True)

st.markdown("""
### Geopolitical Trading Signals & Market Intelligence

Monitor global geopolitical events → generate trading signals with edge quantification.

**Security Note:** This dashboard uses pre-fetched data! API keys are stored securely in GitHub repo secrets and never exposed to the public frontend. 🔐
""")

# Sidebar navigation
with st.sidebar:
    st.header("📍 Navigation")
    
    page = st.radio(
        "Select View",
        ["🎯 Signals", "📰 Articles", "📈 Markets", "🐋 Whales"],
        index=0,
        horizontal=True
    )
    
    st.markdown("---")
    
    # Quick stats from loaded data
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Active Signals", len(signals))
    with col2:
        st.metric("Markets Monitored", len(markets))
    with col3:
        st.metric("Whales Tracked", whales_data.get('total_tracked_usdc', 0) / 1000)

# Main content based on selection
if page == "🎯 Signals":
    st.markdown("<h2 class='section-title'>🎯 Live Trading Signals</h2>", unsafe_allow_html=True)
    
    # Signal cards from loaded JSON data
    for signal in signals:
        confidence_class = signal["confidence"].lower()
        st.markdown(f"""
        <div class="signal-card {confidence_class}">
            <h3>{signal['topic']}</h3>
            <p><strong>Edge:</strong> {signal['edge']} | <strong>Confidence:</strong> {signal['confidence']}</p>
            <p><strong>Direction:</strong> {signal['direction']} ({signal['instrument']})</p>
            <p><strong>Market Price:</strong> ${signal['yes_price']} / No: ${signal['no_price']}</p>
        </div>
        """, unsafe_allow_html=True)

elif page == "📰 Articles":
    st.markdown("<h2 class='section-title'>📰 News Aggregator</h2>", unsafe_allow_html=True)
    
    # Load articles from JSON (RSS feeds aggregated server-side)
    for article in articles:
        st.markdown(f"""
        <div style="border-left: 3px solid #0d1117; padding-left: 1rem; margin: 0.5rem 0;">
            <p><strong>🌍 {article['source']}</strong></p>
            <p>{article['snippet']}</p>
            <a href="{article['url']}" style="color: #58a6ff">Read Article →</a>
        </div>
        """, unsafe_allow_html=True)

elif page == "📈 Markets":
    st.markdown("<h2 class='section-title'>📈 Top Markets by Volume</h2>", unsafe_allow_html=True)
    
    # Markets data from JSON file
    for market in markets:
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric(market['name'], f"{market['yes_price']:.1f}% Yes")
        with col2:
            st.metric("Volume 24h", f"${market['volume_24h_usd']:,}")
        with col3:
            st.write(f"📅 Ends: {market['end_date'][:10]}")

elif page == "🐋 Whales":
    st.markdown("<h2 class='section-title'>🐋 Whale Activity Tracker</h2>", unsafe_allow_html=True)
    
    # Total USDC from whales data
    total_usdc = whales_data.get('total_tracked_usdc', 0)
    
    col1, col2 = st.columns(2)
    with col1:
        st.metric("Total Tracked USDC", f"${total_usdc:,}")
    with col2:
        st.metric("Tracked Wallets", len(whales_data.get('whales', [])))
    
    # Individual whale cards
    for whale in whales_data.get('whales', []):
        col1, col2 = st.columns(2)
        with col1:
            st.markdown(f"""
            <div style="border-left: 3px solid #667eea; background-color: #e7f3ff; padding: 1rem; margin-bottom: 0.5rem;">
                <h4>Whale #{len(whales_data.get('whales', [])) - sum(w == whale for w in whales_data['whales']) + 1}</h4>
                <p><strong>Total USDC:</strong> ${whale['total_usdc']:,}</p>
                <p><strong>Whale Score:</strong> {whale['whale_score']}</p>
            </div>
            """, unsafe_allow_html=True)

st.markdown("---")
st.caption("""
**Powered by:** Pre-fetched JSON data from secure backend  
**Security:** API keys stored in GitHub repo secrets (never public)  
**© 2026 GeoSignal** - All rights reserved | [Privacy Policy](#)
""")
